version: "3"

networks:
  srelearning:
    external: false

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  server:
    image: gitea/gitea:1.16.5
    hostname: gitea
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - ALLOWED_HOST_LIST=192.168.0.9
    restart: always
    networks:
      - srelearning
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"

  jenkins:
    image: jenkins/jenkins:latest
    hostname: jenkins
    container_name: jenkins
    environment:
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins:/var/jenkins_home
    restart: always
    networks:
      - srelearning

  alertmanager:
    container_name: alertmanager
    hostname: alertmanager
    image: prom/alertmanager
    volumes:
      - ./alertmanager.conf:/etc/alertmanager/alertmanager.conf
    command:
      - '--config.file=/etc/alertmanager/alertmanager.conf'
    ports:
      - 9093:9093
    networks:
      - srelearning

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    links:
      - alertmanager:alertmanager
    ports:
      - 9090:9090
    networks:
      - srelearning

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana
    volumes:
      - ./grafana_datasources.yml:/etc/grafana/provisioning/datasources/all.yaml
      - ./grafana_config.ini:/etc/grafana/config.ini
      - grafana_data:/var/lib/grafana
    ports:
      - 3001:3000
    networks:
      - srelearning

#Jenkins token : 64f6e67c8d2643d4709cba8734b640018ac94b62

#git username/password : cbauser/password

#jenkins username/password : cbauser/cbauser

#grafana : admin/password